### ISSUE TITLE
Use relative paths

### ISSUE THREAD

**Issue by PandaWhoCodes** [praveena-sadasivam/spelling-checker#1]
`/Users/ADMIN/Desktop/py/spelling_checker/bloom_filter_english_dictionary.bin`
this will not work on my system or on a server, since I do not have the folders ADMIN Desktop and py.

**Comment by praveena-sadasivam** [comment]
when i use relative path am getting file not found error , but the files are present in same directory . so i have changed it this way
```
import os

THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))

bin_file1 = os.path.join(THIS_FOLDER, 'bloom_filter_english_dictionary.bin')

bin_file2 = os.path.join(THIS_FOLDER, 'bloom_filter_custom_dictionary.bin')

```
